<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net4.8</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>.lib\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>.lib\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="BehaviorDesigner">
        <HintPath>.lib\BehaviorDesigner.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>.lib\BepInEx.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx.Harmony">
        <HintPath>.lib\BepInEx.Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Rewired_Core">
        <HintPath>.lib\Rewired_Core.dll</HintPath>
      </Reference>
      <Reference Include="UnderMine">
        <HintPath>.lib\UnderMine.dll</HintPath>
      </Reference>
      <Reference Include="Unity.TextMeshPro">
        <HintPath>.lib\Unity.TextMeshPro.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>.lib\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>.lib\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextCoreModule">
        <HintPath>.lib\UnityEngine.TextCoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.TextRenderingModule">
        <HintPath>.lib\UnityEngine.TextRenderingModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>.lib\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>.lib\UnityEngine.UIModule.dll</HintPath>
      </Reference>
      <Reference Include="KeybindLib">
        <HintPath>.lib\KeybindLib.dll</HintPath>
      </Reference>
    </ItemGroup>
</Project>
